-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.cities CASCADE;
DROP TABLE IF EXISTS public.patients CASCADE;
DROP TABLE IF EXISTS public.periods CASCADE;
DROP TABLE IF EXISTS public.results CASCADE;
DROP TABLE IF EXISTS public.wards_departments CASCADE;
DROP TABLE IF EXISTS public.wards CASCADE;
DROP TABLE IF EXISTS public.departments CASCADE;
DROP TABLE IF EXISTS public.phones CASCADE;

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id serial,
    city_name character varying(32) NOT NULL,
    PRIMARY KEY (city_id),
    UNIQUE (city_name)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    patient_id serial,
    last_name character varying(32) NOT NULL,
    first_name character varying(32) NOT NULL,
    middle_name character varying(32),
    insurance_number character varying(50),
    is_paid boolean NOT NULL,
    created_at date NOT NULL DEFAULT current_date,
    postal_code character(6),
    city_id integer NOT NULL,
    street character varying(100),
    house character varying(10),
    building character varying(10),
    apartment character varying(10),
    passport_series character varying(4) NOT NULL,
    passport_number character varying(6) NOT NULL,
    birth_date date NOT NULL,
    birth_place character varying(100),
    issued_by character varying(150),
    issued_date date,
    department_code character(7),
    allergies text,
    PRIMARY KEY (patient_id),
    UNIQUE (insurance_number),
    UNIQUE (passport_series, passport_number),
	CHECK (passport_series ~ '^[0-9]{4}$'),
	CHECK (passport_number ~ '^[0-9]{6}$'),
	CHECK (postal_code IS NULL OR postal_code ~ '^[0-9]{6}$')
);

CREATE TABLE IF NOT EXISTS public.periods
(
    period_id serial,
    patient_id integer NOT NULL,
    admission_date date NOT NULL,
    admission_reason text NOT NULL,
    discharge_date date,
    discharge_summary text,
    wd_id integer,
    PRIMARY KEY (period_id),
	CHECK (discharge_date IS NULL 
	OR discharge_date>=admission_date) --дата выписки после поступления
);

CREATE TABLE IF NOT EXISTS public.results
(
    result_id serial,
    period_id integer NOT NULL,
    action_date date NOT NULL,
    action_name character varying(255) NOT NULL,
    action_reason text,
    initial_exam text,
    action_result text,
    treatment_plan text,
    conclusion text,
    PRIMARY KEY (result_id)
);

CREATE TABLE IF NOT EXISTS public.wards_departments
(
    wd_id serial,
    ward_id integer NOT NULL,
    department_id integer NOT NULL,
    PRIMARY KEY (wd_id),
    UNIQUE (ward_id, department_id)
);

CREATE TABLE IF NOT EXISTS public.wards
(
    ward_id serial,
    floor integer NOT NULL,
    capacity integer NOT NULL,
    PRIMARY KEY (ward_id)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    department_id serial,
    department_name character varying(64) NOT NULL,
    PRIMARY KEY (department_id),
    UNIQUE (department_name)
);

CREATE TABLE IF NOT EXISTS public.phones
(
    phone character varying(20),
    patient_id integer,
    PRIMARY KEY (phone, patient_id),
	CHECK (phone ~ '^\+7[0-9]{10}$')
);

ALTER TABLE IF EXISTS public.patients
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.periods
    ADD FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.periods
    ADD FOREIGN KEY (wd_id)
    REFERENCES public.wards_departments (wd_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.results
    ADD FOREIGN KEY (period_id)
    REFERENCES public.periods (period_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.wards_departments
    ADD FOREIGN KEY (department_id)
    REFERENCES public.departments (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.wards_departments
    ADD FOREIGN KEY (ward_id)
    REFERENCES public.wards (ward_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.phones
    ADD FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;